language: php

php:
  - 5.5

sudo: false

services: mongodb

before_install:
    - composer self-update

install:
    - composer --prefer-source install

notifications:
  email:
    - payumsupport@forma-pro.com
